python train_fn.py \
  --data_path trn.clean.jsonl \
  --model_name google/flan-t5-base \
  --output_dir ./models/flan_t5_a10_lora \
  --peft true \
  --lora_r 16 \
  --lora_alpha 32 \
  --lora_dropout 0.05 \
  --load_in_8bit true \
  --per_device_train_batch_size 8 \
  --gradient_accumulation_steps 2 \
  --max_source_length 256 \
  --max_target_length 256 \
  --learning_rate 2e-4 \
  --num_train_epochs 1 \
  --run_baseline true \
  --do_eval true \
  --merge_lora true